# Generated by Django 4.2.1 on 2023-06-06 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grade_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('cohorts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cohorts')),
            ],
            options={
                'ordering': ['-grade'],
            },
        ),
        migrations.AddField(
            model_name='cohorts',
            name='students',
            field=models.ManyToManyField(to='main_app.student'),
        ),
    ]
