# Generated by Django 4.2.1 on 2023-06-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Due Date')),
                ('assignment', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cohorts')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
