# Generated by Django 4.2.1 on 2023-06-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_student_grades_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_grades',
            options={},
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
