# Generated by Django 4.2.1 on 2023-06-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_student_grades_options_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_grades',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('F', 'F')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
